import { type MasterRule } from "./model";

type AdditionalRule = Pick<
  MasterRule,
  | "id"
  | "name"
  | "category"
  | "modalities"
  | "level"
  | "variable"
  | "dataSource"
  | "defaultOperator"
  | "readiness"
  | "requiredData"
>;

const additionalRule = (rule: AdditionalRule): MasterRule => ({
  ...rule,
  description: `${rule.name}, conforme parâmetro definido pela política aplicável.`,
  technicalMessage: `${rule.variable} deve atender ao parâmetro vigente.`,
  friendlyMessage: `${rule.name} não atende ao parâmetro da política.`,
});

const additionalRules: MasterRule[] = [
  [
    "TITLE-ISSUE-DATE-REQUIRED-001",
    "Data de emissão informada",
    "DOCUMENTACAO",
    "TITULO",
    "issueDatePresent",
    "operation.manualEntry.entries.issueDate",
    "EQ",
    "REQUER_DADO",
    "Data de emissão normalizada",
  ],
  [
    "TITLE-DOCUMENT-REQUIRED-001",
    "Número do documento informado",
    "DOCUMENTACAO",
    "TITULO",
    "documentNumberPresent",
    "operation.manualEntry.entries.documentNumber",
    "EQ",
    "REQUER_DADO",
    "Documento normalizado",
  ],
  [
    "TITLE-DEBTOR-DOCUMENT-REQUIRED-001",
    "Documento do sacado informado",
    "CADASTRO",
    "TITULO",
    "debtorDocumentPresent",
    "operation.manualEntry.entries.debtorDocument",
    "EQ",
    "REQUER_DADO",
    "CPF/CNPJ validado",
  ],
  [
    "TITLE-NFE-VALID-001",
    "NF-e válida na SEFAZ",
    "LASTRO",
    "TITULO",
    "fiscalEvidenceValid",
    "sefaz.nfe.status",
    "EQ",
    "REQUER_INTEGRACAO",
    "Consulta SEFAZ",
  ],
  [
    "TITLE-OWNERSHIP-VALID-001",
    "Titularidade do recebível",
    "TITULARIDADE",
    "TITULO",
    "ownershipValid",
    "registry.ownership",
    "EQ",
    "REQUER_INTEGRACAO",
    "Registradora ou custodiante",
  ],
  [
    "TITLE-REGISTRATION-VALID-001",
    "Registro do recebível",
    "REGISTRO",
    "TITULO",
    "registrationValid",
    "registry.receivable.status",
    "EQ",
    "REQUER_INTEGRACAO",
    "Registradora de recebíveis",
  ],
  [
    "TITLE-LIEN-FREE-001",
    "Ausência de gravame impeditivo",
    "ONUS",
    "TITULO",
    "freeOfBlockingLien",
    "registry.liens",
    "EQ",
    "REQUER_INTEGRACAO",
    "Consulta de gravames",
  ],
  [
    "TITLE-CONFIRMATION-REQUIRED-001",
    "Confirmação do recebível",
    "CHECAGEM",
    "TITULO",
    "confirmationStatus",
    "lastroReview.confirmation",
    "IN",
    "REQUER_DADO",
    "Resultado da checagem",
  ],
  [
    "TITLE-STATE-ALLOWED-001",
    "UF do sacado permitida",
    "GEOGRAFIA",
    "TITULO",
    "debtorState",
    "operation.manualEntry.entries.state",
    "IN",
    "REQUER_DADO",
    "Endereço cadastral do sacado",
  ],
  [
    "TITLE-RECEIVABLE-TYPE-ALLOWED-001",
    "Tipo de recebível permitido",
    "NATUREZA",
    "TITULO",
    "receivableType",
    "operation.manualEntry.receivableType",
    "IN",
    "REQUER_DADO",
    "Natureza padronizada do ativo",
  ],

  [
    "DEBTOR-REGISTRATION-ACTIVE-001",
    "Situação cadastral do sacado",
    "CADASTRO",
    "SACADO",
    "registrationActive",
    "registry.debtor.status",
    "EQ",
    "REQUER_INTEGRACAO",
    "Receita Federal ou cadastro equivalente",
  ],
  [
    "DEBTOR-LIMIT-USAGE-MAX-001",
    "Utilização projetada do limite do sacado",
    "LIMITE",
    "SACADO",
    "projectedLimitUsagePercent",
    "debtor.limit",
    "LTE",
    "REQUER_DADO",
    "Limite individual do sacado",
  ],
  [
    "DEBTOR-PORTFOLIO-CONCENTRATION-MAX-001",
    "Concentração do sacado na carteira",
    "CONCENTRACAO",
    "SACADO",
    "portfolioConcentrationPercent",
    "portfolio.byDebtor",
    "LTE",
    "REQUER_DADO",
    "Exposição consolidada da carteira",
  ],
  [
    "DEBTOR-GROUP-CONCENTRATION-MAX-001",
    "Concentração do grupo econômico do sacado",
    "GRUPO_ECONOMICO",
    "SACADO",
    "groupConcentrationPercent",
    "registry.economicGroup",
    "LTE",
    "REQUER_DADO",
    "Vínculos de grupo econômico",
  ],
  [
    "DEBTOR-EXTERNAL-SCORE-MIN-001",
    "Score externo mínimo do sacado",
    "BUREAU",
    "SACADO",
    "externalScore",
    "bureau.score",
    "GTE",
    "REQUER_INTEGRACAO",
    "Bureau contratado",
  ],
  [
    "DEBTOR-INTERNAL-SCORE-MIN-001",
    "Score interno mínimo do sacado",
    "SCORE_INTERNO",
    "SACADO",
    "internalScore",
    "scoreEngine.debtor",
    "GTE",
    "REQUER_DADO",
    "Modelo proprietário homologado",
  ],
  [
    "DEBTOR-RESTRICTIONS-MAX-001",
    "Restrições do sacado",
    "RESTRICAO",
    "SACADO",
    "restrictionCount",
    "bureau.restrictions",
    "LTE",
    "REQUER_INTEGRACAO",
    "Bureau e fontes públicas",
  ],
  [
    "DEBTOR-AVERAGE-DELAY-MAX-001",
    "Atraso médio do sacado",
    "PERFORMANCE",
    "SACADO",
    "averageDelayDays",
    "debtor.averageDelayDays",
    "LTE",
    "REQUER_DADO",
    "Histórico de liquidações",
  ],
  [
    "DEBTOR-OVERDUE-PERCENT-MAX-001",
    "Inadimplência do sacado",
    "INADIMPLENCIA",
    "SACADO",
    "overduePercent",
    "debtor.portfolio",
    "LTE",
    "REQUER_DADO",
    "Carteira consolidada do sacado",
  ],

  [
    "CEDENT-REGISTRATION-ACTIVE-001",
    "Situação cadastral do cedente",
    "CADASTRO",
    "CEDENTE",
    "registrationActive",
    "registry.cedent.status",
    "EQ",
    "REQUER_INTEGRACAO",
    "Receita Federal ou cadastro equivalente",
  ],
  [
    "CEDENT-EXTERNAL-SCORE-MIN-001",
    "Score externo mínimo do cedente",
    "BUREAU",
    "CEDENTE",
    "externalScore",
    "bureau.score",
    "GTE",
    "REQUER_INTEGRACAO",
    "Bureau contratado",
  ],
  [
    "CEDENT-INTERNAL-SCORE-MIN-001",
    "Score interno mínimo do cedente",
    "SCORE_INTERNO",
    "CEDENTE",
    "internalScore",
    "scoreEngine.cedent",
    "GTE",
    "REQUER_DADO",
    "Modelo proprietário homologado",
  ],
  [
    "CEDENT-AVERAGE-DELAY-MAX-001",
    "Atraso médio da carteira do cedente",
    "PERFORMANCE",
    "CEDENTE",
    "averageDelayDays",
    "cedent.averageDelayDays",
    "LTE",
    "REQUER_DADO",
    "Histórico operacional",
  ],
  [
    "CEDENT-REPURCHASE-MAX-001",
    "Índice de recompra do cedente",
    "RECOMPRA",
    "CEDENTE",
    "repurchasePercent",
    "cedent.repurchaseHistory",
    "LTE",
    "REQUER_DADO",
    "Histórico de recompras",
  ],
  [
    "CEDENT-DILUTION-MAX-001",
    "Índice de diluição do cedente",
    "DILUICAO",
    "CEDENTE",
    "dilutionPercent",
    "cedent.dilutionHistory",
    "LTE",
    "REQUER_DADO",
    "Baixas e cancelamentos históricos",
  ],
  [
    "CEDENT-RESTRICTIONS-MAX-001",
    "Restrições do cedente",
    "RESTRICAO",
    "CEDENTE",
    "restrictionCount",
    "bureau.restrictions",
    "LTE",
    "REQUER_INTEGRACAO",
    "Bureau e fontes públicas",
  ],
  [
    "CEDENT-FINANCIALS-RECENCY-MAX-001",
    "Atualidade das demonstrações financeiras",
    "FINANCEIRO",
    "CEDENTE",
    "financialStatementAgeDays",
    "registry.financialStatements",
    "LTE",
    "REQUER_DADO",
    "Balanços e balancetes",
  ],

  [
    "OPERATION-AMOUNT-MIN-001",
    "Valor mínimo da operação",
    "VALOR",
    "OPERACAO",
    "grossAmount",
    "operation.amount",
    "GTE",
    "REQUER_DADO",
    "Valor bruto normalizado",
  ],
  [
    "OPERATION-AMOUNT-MAX-001",
    "Valor máximo da operação",
    "VALOR",
    "OPERACAO",
    "grossAmount",
    "operation.amount",
    "LTE",
    "REQUER_DADO",
    "Valor bruto normalizado",
  ],
  [
    "OPERATION-TITLE-COUNT-MIN-001",
    "Quantidade mínima de títulos",
    "QUANTIDADE",
    "OPERACAO",
    "titleCount",
    "operation.titleCount",
    "GTE",
    "REQUER_DADO",
    "Contagem conciliada de títulos",
  ],
  [
    "OPERATION-TITLE-COUNT-MAX-001",
    "Quantidade máxima de títulos",
    "QUANTIDADE",
    "OPERACAO",
    "titleCount",
    "operation.titleCount",
    "LTE",
    "REQUER_DADO",
    "Contagem conciliada de títulos",
  ],
  [
    "OPERATION-WEIGHTED-TERM-MAX-001",
    "Prazo médio ponderado máximo",
    "PRAZO",
    "OPERACAO",
    "weightedAverageTermDays",
    "pricing.weightedAverageTerm",
    "LTE",
    "REQUER_DADO",
    "Fluxo de vencimentos",
  ],
  [
    "OPERATION-MIN-PROFITABILITY-001",
    "Rentabilidade mínima da operação",
    "RENTABILIDADE",
    "OPERACAO",
    "profitabilityPercent",
    "pricing.profitability",
    "GTE",
    "REQUER_DADO",
    "Precificação concluída",
  ],
  [
    "OPERATION-RATE-MIN-001",
    "Taxa mínima da operação",
    "PRECO",
    "OPERACAO",
    "monthlyRatePercent",
    "pricing.monthlyRate",
    "GTE",
    "REQUER_DADO",
    "Condição comercial salva",
  ],
  [
    "OPERATION-FEES-CONSISTENT-001",
    "Tarifas consistentes com a política",
    "PRECO",
    "OPERACAO",
    "feesConsistent",
    "pricing.fees",
    "EQ",
    "REQUER_DADO",
    "Tabela de tarifas aplicável",
  ],

  [
    "PORTFOLIO-DEBTOR-CONCENTRATION-MAX-001",
    "Concentração máxima por sacado na carteira",
    "CONCENTRACAO",
    "CARTEIRA",
    "largestDebtorConcentrationPercent",
    "portfolio.byDebtor",
    "LTE",
    "REQUER_DADO",
    "Carteira projetada consolidada",
  ],
  [
    "PORTFOLIO-GROUP-CONCENTRATION-MAX-001",
    "Concentração máxima por grupo econômico",
    "GRUPO_ECONOMICO",
    "CARTEIRA",
    "largestGroupConcentrationPercent",
    "portfolio.byEconomicGroup",
    "LTE",
    "REQUER_DADO",
    "Grupos econômicos consolidados",
  ],
  [
    "PORTFOLIO-OVERDUE-MAX-001",
    "Inadimplência máxima da carteira",
    "INADIMPLENCIA",
    "CARTEIRA",
    "overduePercent",
    "portfolio.aging",
    "LTE",
    "REQUER_DADO",
    "Aging consolidado",
  ],
  [
    "PORTFOLIO-LONG-AGING-MAX-001",
    "Exposição máxima no aging longo",
    "AGING",
    "CARTEIRA",
    "longAgingPercent",
    "portfolio.aging",
    "LTE",
    "REQUER_DADO",
    "Faixas de atraso da carteira",
  ],
  [
    "PORTFOLIO-MATURITY-CONCENTRATION-MAX-001",
    "Concentração máxima por vencimento",
    "VENCIMENTO",
    "CARTEIRA",
    "maturityConcentrationPercent",
    "portfolio.maturity",
    "LTE",
    "REQUER_DADO",
    "Calendário projetado da carteira",
  ],
  [
    "PORTFOLIO-DIVERSIFICATION-MIN-001",
    "Diversificação mínima da carteira",
    "DIVERSIFICACAO",
    "CARTEIRA",
    "activeDebtorCount",
    "portfolio.byDebtor",
    "GTE",
    "REQUER_DADO",
    "Quantidade de sacados ativos",
  ],

  [
    "STRUCTURE-ASSIGNMENT-FORMALIZED-001",
    "Cessão formalizada",
    "CESSAO",
    "ESTRUTURA",
    "assignmentFormalized",
    "legal.assignment",
    "EQ",
    "REQUER_DADO",
    "Documentação de cessão",
  ],
  [
    "STRUCTURE-REGISTRATION-COMPLETE-001",
    "Registro da estrutura concluído",
    "REGISTRO",
    "ESTRUTURA",
    "structureRegistrationComplete",
    "registry.structure",
    "EQ",
    "REQUER_INTEGRACAO",
    "Registradora ou custodiante",
  ],
  [
    "STRUCTURE-GUARANTEE-COVERAGE-MIN-001",
    "Cobertura mínima de garantias",
    "GARANTIA",
    "ESTRUTURA",
    "guaranteeCoveragePercent",
    "guarantees.coverage",
    "GTE",
    "REQUER_DADO",
    "Garantias formalizadas e avaliadas",
  ],
  [
    "STRUCTURE-FUNDING-LIMIT-AVAILABLE-001",
    "Limite disponível na estrutura de funding",
    "FUNDING",
    "ESTRUTURA",
    "fundingLimitAvailable",
    "funding.availableLimit",
    "EQ",
    "REQUER_INTEGRACAO",
    "Posição da fonte de funding",
  ],
  [
    "FIDC-REGULATION-ELIGIBILITY-001",
    "Enquadramento ao regulamento do FIDC",
    "ESTRUTURA_FIDC",
    "ESTRUTURA",
    "fundRegulationEligible",
    "fund.regulation",
    "EQ",
    "REQUER_DADO",
    "Regulamento traduzido em parâmetros",
    ["FIDC"],
  ],
  [
    "SECURITIZATION-ISSUE-ELIGIBILITY-001",
    "Enquadramento à emissão",
    "ESTRUTURA_SECURITIZACAO",
    "ESTRUTURA",
    "issuanceEligible",
    "securitization.issuance",
    "EQ",
    "REQUER_DADO",
    "Documentos da emissão",
    ["Securitizadora"],
  ],
].map(item => {
  const [id, name, category, level, variable, dataSource, defaultOperator, readiness, requiredData, modalities] =
    item as [
      string,
      string,
      string,
      MasterRule["level"],
      string,
      string,
      MasterRule["defaultOperator"],
      MasterRule["readiness"],
      string,
      MasterRule["modalities"]?,
    ];
  return additionalRule({
    id,
    name,
    category,
    level,
    variable,
    dataSource,
    defaultOperator,
    readiness,
    requiredData,
    modalities: modalities ?? ["TODAS"],
  });
});

/**
 * Matriz Mestre inicial. Não contém limites numéricos: parâmetros pertencem às políticas versionadas.
 */
export const masterRuleCatalog: MasterRule[] = [
  {
    id: "TITLE-AMOUNT-MIN-001",
    name: "Valor mínimo do título",
    description: "Compara o valor de face do título com o mínimo definido pela política.",
    category: "VALOR",
    modalities: ["TODAS"],
    level: "TITULO",
    variable: "faceAmount",
    dataSource: "operation.manualEntry.entries.amount",
    defaultOperator: "GTE",
    technicalMessage: "faceAmount deve atender ao parâmetro mínimo vigente.",
    friendlyMessage: "O valor do título está abaixo do mínimo permitido pela política.",
  },
  {
    id: "TITLE-TERM-MAX-001",
    name: "Prazo máximo do título",
    description: "Compara o prazo corrido do título com o máximo definido pela política.",
    category: "PRAZO",
    modalities: ["TODAS"],
    level: "TITULO",
    variable: "termDays",
    dataSource: "operation.manualEntry.entries.dueDate",
    defaultOperator: "LTE",
    technicalMessage: "termDays deve atender ao parâmetro máximo vigente.",
    friendlyMessage: "O prazo do título excede o máximo permitido pela política.",
  },
  {
    id: "TITLE-DUPLICATE-001",
    name: "Duplicidade na operação",
    description: "Identifica documento repetido entre os títulos disponíveis da operação.",
    category: "INTEGRIDADE",
    modalities: ["TODAS"],
    level: "TITULO",
    variable: "duplicateInOperation",
    dataSource: "operation.manualEntry.entries.documentNumber",
    defaultOperator: "EQ",
    technicalMessage: "duplicateInOperation deve ser falso.",
    friendlyMessage: "O documento aparece mais de uma vez na operação.",
  },
  {
    id: "TITLE-FISCAL-EVIDENCE-001",
    name: "Evidência fiscal informada",
    description: "Verifica a presença da chave fiscal relacionada ao recebível.",
    category: "LASTRO",
    modalities: ["TODAS"],
    level: "TITULO",
    variable: "hasFiscalEvidence",
    dataSource: "operation.manualEntry.entries.nfeKey",
    defaultOperator: "EQ",
    technicalMessage: "hasFiscalEvidence deve ser verdadeiro quando exigido pela política.",
    friendlyMessage: "A evidência fiscal do título ainda não está disponível.",
  },
  {
    id: "DEBTOR-OPERATION-CONCENTRATION-MAX-001",
    name: "Concentração máxima do sacado na operação",
    description: "Compara a participação do sacado no valor disponível da operação.",
    category: "CONCENTRACAO",
    modalities: ["TODAS"],
    level: "SACADO",
    variable: "operationConcentrationPercent",
    dataSource: "operation.manualEntry.entries.amount / operation.amount",
    defaultOperator: "LTE",
    technicalMessage: "operationConcentrationPercent deve atender ao parâmetro máximo vigente.",
    friendlyMessage: "A concentração projetada do sacado excede o limite da política.",
  },
  {
    id: "CEDENT-PROJECTED-LIMIT-USAGE-MAX-001",
    name: "Utilização projetada do limite do cedente",
    description: "Compara limite utilizado mais a nova operação com o limite de crédito vigente.",
    category: "LIMITE",
    modalities: ["TODAS"],
    level: "CEDENTE",
    variable: "projectedLimitUsagePercent",
    dataSource: "(cedent.usedLimit + operation.amount) / cedent.creditLimit",
    defaultOperator: "LTE",
    technicalMessage: "projectedLimitUsagePercent deve atender ao parâmetro máximo vigente.",
    friendlyMessage: "A operação elevaria a utilização do limite do cedente acima do permitido.",
  },
  {
    id: "OPERATION-TITLE-SUM-MATCH-001",
    name: "Conciliação do valor da operação",
    description: "Verifica se a soma dos títulos disponíveis coincide com o valor bruto informado.",
    category: "INTEGRIDADE",
    modalities: ["TODAS"],
    level: "OPERACAO",
    variable: "titlesMatchGrossAmount",
    dataSource: "sum(operation.manualEntry.entries.amount) = operation.amount",
    defaultOperator: "EQ",
    technicalMessage: "titlesMatchGrossAmount deve ser verdadeiro.",
    friendlyMessage: "A soma dos títulos não coincide com o valor bruto da operação.",
  },
  {
    id: "OPERATION-NET-AMOUNT-VALID-001",
    name: "Valor líquido consistente",
    description: "Verifica se o líquido é positivo e não supera o valor bruto da operação.",
    category: "INTEGRIDADE",
    modalities: ["TODAS"],
    level: "OPERACAO",
    variable: "netAmountValid",
    dataSource: "operation.netAmount <= operation.amount",
    defaultOperator: "EQ",
    technicalMessage: "netAmountValid deve ser verdadeiro.",
    friendlyMessage: "O valor líquido informado é inconsistente com o valor bruto.",
  },
  {
    id: "PORTFOLIO-CEDENT-OVERDUE-MAX-001",
    name: "Inadimplência máxima da carteira do cedente",
    description: "Compara o vencido do cedente com sua carteira total em aberto.",
    category: "CARTEIRA",
    modalities: ["TODAS"],
    level: "CARTEIRA",
    variable: "cedentOverduePercent",
    dataSource: "cedent.portfolioOverdue / cedent.portfolioReceivable",
    defaultOperator: "LTE",
    technicalMessage: "cedentOverduePercent deve atender ao parâmetro máximo vigente.",
    friendlyMessage: "A inadimplência da carteira do cedente excede o limite da política.",
  },
  {
    id: "STRUCTURE-DEFINED-001",
    name: "Estrutura operacional definida",
    description: "Confirma que modalidade e veículo da operação foram definidos.",
    category: "ESTRUTURA",
    modalities: ["TODAS"],
    level: "ESTRUTURA",
    variable: "structureDefined",
    dataSource: "operation.institution + operation.vehicle",
    defaultOperator: "EQ",
    technicalMessage: "structureDefined deve ser verdadeiro.",
    friendlyMessage: "A modalidade ou o veículo da operação não foi definido.",
  },
  {
    id: "FIDC-FUND-CLASS-REQUIRED-001",
    name: "Classe do fundo informada",
    description: "Confirma a classe ou subclasse aplicável à operação de FIDC.",
    category: "ESTRUTURA_FIDC",
    modalities: ["FIDC"],
    level: "ESTRUTURA",
    variable: "fundClassPresent",
    dataSource: "operation.fundClass",
    defaultOperator: "EQ",
    technicalMessage: "fundClassPresent deve ser verdadeiro no perfil FIDC.",
    friendlyMessage: "A classe ou subclasse aplicável ao FIDC não foi informada.",
  },
  ...additionalRules,
];
