/**
 * Sacados de demonstração com score, histórico de liquidação e grupo econômico.
 */
import { type Debtor } from "@/src/domain/core/types";
export const initialDebtors: Debtor[] = [
  {
    id: "sacado-1",
    document: "44.659.901/0001-65",
    name: "L.V. Carvalho Gutierrez Ltda",
    tradeName: "L.V. Carvalho",
    address: "Rua Paraná",
    number: "1511",
    district: "Centro",
    city: "Cascavel",
    state: "PR",
    zipCode: "85801-050",
    email: "financeiro@lvcarvalho.com.br",
    phone: "(45) 3035-4100",
    source: "Sistema",
    score: 812,
    portfolioReceivable: 486834.22,
    portfolioOverdue: 0,
    settlements: 42,
    lateSettlements: 1,
    averageDelayDays: 1,
    repurchases: 0,
    incidents: 0,
    publicStatus: "Ativa e regular",
    scoreReasons: [
      "Carteira sem títulos vencidos",
      "42 liquidações com atraso médio de 1 dia",
      "Nenhuma recompra registrada",
      "Cadastro público regular",
    ],
    portfolioMetrics: {
      settledOnTime: { count: 41, amount: 1280430.18 },
      settledLate: { count: 1, amount: 28400 },
      repurchased: { count: 0, amount: 0 },
      protested: { count: 0, amount: 0 },
      courtSettled: { count: 0, amount: 0 },
      extendedSettled: { count: 1, amount: 19800 },
      openDue: { count: 9, amount: 486834.22 },
      openOverdue: { count: 0, amount: 0 },
      openExtended: { count: 0, amount: 0 },
      openNegotiation: { count: 0, amount: 0 },
      concentrationPercent: 18.4,
    },
    groupName: "Grupo Carvalho",
    groupCompanies: 3,
    groupExposure: 724190.8,
    groupOverdue: 0,
    groupScore: 784,
  },
  {
    id: "sacado-2",
    document: "07.583.481/0001-54",
    name: "Carlos Marco Distribuidora Ltda",
    tradeName: "Carlos Marco",
    address: "Av. Brasil",
    number: "2840",
    district: "São Cristóvão",
    city: "Cascavel",
    state: "PR",
    zipCode: "85816-290",
    phone: "(45) 3224-8890",
    source: "Sistema",
    score: 548,
    portfolioReceivable: 192450,
    portfolioOverdue: 28600,
    settlements: 19,
    lateSettlements: 6,
    averageDelayDays: 12,
    repurchases: 2,
    incidents: 1,
    publicStatus: "Ativa · 1 apontamento cadastral",
    scoreReasons: [
      "R$ 28.600,00 vencidos na carteira",
      "6 de 19 liquidações ocorreram após o vencimento",
      "Atraso médio de 12 dias",
      "2 recompras registradas",
    ],
    incidentDetails: ["Apontamento cadastral em monitoramento"],
    portfolioMetrics: {
      settledOnTime: { count: 13, amount: 552000 },
      settledLate: { count: 6, amount: 184900 },
      repurchased: { count: 2, amount: 48000 },
      protested: { count: 1, amount: 19000 },
      courtSettled: { count: 0, amount: 0 },
      extendedSettled: { count: 2, amount: 74000 },
      openDue: { count: 5, amount: 163850 },
      openOverdue: { count: 2, amount: 28600 },
      openExtended: { count: 1, amount: 22600 },
      openNegotiation: { count: 1, amount: 28600 },
      concentrationPercent: 11.2,
    },
    groupName: "Grupo Marco",
    groupCompanies: 2,
    groupExposure: 338900,
    groupOverdue: 42600,
    groupScore: 526,
  },
  {
    id: "sacado-3",
    document: "75.846.394/0001-00",
    name: "Supermercado Haag Ltda",
    address: "Rua das Flores",
    number: "830",
    district: "Jardim América",
    city: "Toledo",
    state: "PR",
    zipCode: "85905-180",
    email: "contato@haag.com.br",
    source: "Sistema",
    score: 721,
    portfolioReceivable: 118900,
    portfolioOverdue: 4200,
    settlements: 31,
    lateSettlements: 3,
    averageDelayDays: 4,
    repurchases: 1,
    incidents: 0,
    publicStatus: "Ativa e regular",
    scoreReasons: [
      "Baixa proporção de vencidos na carteira",
      "31 liquidações no histórico",
      "Atraso médio controlado em 4 dias",
      "Cadastro público regular",
    ],
    portfolioMetrics: {
      settledOnTime: { count: 28, amount: 910400 },
      settledLate: { count: 3, amount: 103200 },
      repurchased: { count: 1, amount: 29000 },
      protested: { count: 0, amount: 0 },
      courtSettled: { count: 0, amount: 0 },
      extendedSettled: { count: 2, amount: 54000 },
      openDue: { count: 4, amount: 114700 },
      openOverdue: { count: 1, amount: 4200 },
      openExtended: { count: 1, amount: 31000 },
      openNegotiation: { count: 0, amount: 0 },
      concentrationPercent: 7.6,
    },
    groupName: "Grupo Haag",
    groupCompanies: 4,
    groupExposure: 582440,
    groupOverdue: 12300,
    groupScore: 698,
  },
  {
    id: "sacado-4",
    document: "31.998.442/0001-00",
    name: "Empório Central Ltda",
    address: "Rua XV de Novembro",
    number: "1204",
    district: "Centro",
    city: "Campinas",
    state: "SP",
    zipCode: "13010-111",
    email: "financeiro@emporiocentral.com.br",
    source: "Sistema",
    score: 702,
    portfolioReceivable: 86400,
    portfolioOverdue: 0,
    settlements: 44,
    lateSettlements: 4,
    averageDelayDays: 3,
    repurchases: 0,
    incidents: 0,
    publicStatus: "Ativa e regular",
    scoreReasons: [
      "Sem vencidos na carteira",
      "44 liquidações no histórico",
      "Atraso médio de 3 dias",
      "Cadastro público regular",
    ],
  },
  {
    id: "sacado-5",
    document: "18.443.120/0001-29",
    name: "Presentes Sul Comércio Ltda",
    address: "Av. Brasil",
    number: "455",
    district: "Vila Industrial",
    city: "Campinas",
    state: "SP",
    zipCode: "13035-270",
    email: "contas@presentessul.com.br",
    source: "Sistema",
    score: 676,
    portfolioReceivable: 64200,
    portfolioOverdue: 0,
    settlements: 28,
    lateSettlements: 5,
    averageDelayDays: 5,
    repurchases: 0,
    incidents: 0,
    publicStatus: "Ativa e regular",
    scoreReasons: [
      "Sem vencidos na carteira",
      "28 liquidações no histórico",
      "Atraso médio de 5 dias",
      "Cadastro público regular",
    ],
  },
  {
    id: "sacado-6",
    document: "25.410.398/0001-65",
    name: "Comercial Oeste Ltda",
    address: "Rua Sete de Setembro",
    number: "88",
    district: "Centro",
    city: "Sorocaba",
    state: "SP",
    zipCode: "18035-000",
    email: "financeiro@comercialoeste.com.br",
    source: "Sistema",
    portfolioReceivable: 0,
    portfolioOverdue: 0,
    settlements: 0,
    lateSettlements: 0,
    averageDelayDays: 0,
    repurchases: 0,
    incidents: 0,
    publicStatus: "Ativa e regular",
    scoreReasons: ["Sacado novo: sem histórico no ambiente"],
  },
];
